version: '3.8'

services:
  php:
    build:
      context: .
    container_name: php
    volumes:
      - .:/var/www/html
    networks:
      - symfony_network
    environment:
      - SYMFONY_ENV=dev
    depends_on:
      - mysql
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - symfony_network
    depends_on:
      - php
    ports:
      - "80:80"


  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony_network
    ports:
      - "3306:3306"

volumes:
  mysql_data:
    driver: local

networks:
  symfony_network:
    driver: bridge
